version: '2'
networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: ${MTU}

services:
    postgres:
        container_name: "postgres"
        restart: "always"
        image: "${NEXUS_REPO}/onap/refrepo/postgres:${POSTGRES_TAG}"
        mem_limit: "1g"
        memswap_limit: "1g"
        ports:
         - "5432:5432"   

    refrepo:
        container_name: "refrepo"
        restart: "always"
        image: "${NEXUS_REPO}/onap/refrepo:${REFREPO_TAG}"
        ports:
            - "8702-8703:8702-8703"
        environment:
            POSTGRES_IP: postgres
        volumes:
            - /data/csars:/service/webapps/ROOT/WEB-INF/tomcat/webapps/ROOT/CSAR
        links:
            - postgres
